[package]
name = "salesman_problem"
version = "0.1.0"
authors = ["Matrosov Sergey <matrosik14@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7"
gnuplot = "0.0.37"